global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-mÃªme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot app
  - job_name: 'adoption-spring-app'
    metrics_path: '/adoption/actuator/prometheus'
    static_configs:
      - targets: ['adoption-app:8089']
    scrape_interval: 10s

  # MySQL metrics (optionnel, si tu ajoutes mysqld_exporter)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
