global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'adoption-backend'
    metrics_path: '/adoption/actuator/prometheus'
    static_configs:
      - targets: ['adoption-app:8089']  # ✅ Changez ICI : nom de SERVICE pas de CONTAINER
    scrape_interval: 10s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # ✅ Déjà correct
    scrape_interval: 10s


  - job_name: 'mysql'
    static_configs:
      - targets: [ 'mysql-db:3306' ]  # Nécessite mysqld_exporter
    scrape_interval: 15s
