global:
  scrape_interval: 10s  # Fréquence de récupération des métriques
  evaluation_interval: 10s

scrape_configs:
  # Scrape Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape l’application Spring Boot (ou autre service exposant des métriques)
  - job_name: 'adoption-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['adoption-backend:8089']

  # Scrape Grafana (optionnel, si tu veux monitorer Grafana lui-même)
  - job_name: 'grafana'
    static_configs:
      - targets: ['adoption-grafana:3000']
