global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'adoption-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['adoption-spring-app:8089']

  - job_name: 'grafana'
    static_configs:
      - targets: ['adoption-grafana:3000']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['cadvisor:8080']
